### ISSUE TITLE
Service properties not working inside resource drop-ins

### ISSUE THREAD

**Issue by hugo-cisneiros-movile** [nathwill/chef-systemd#125]
I updated the cookbook version to 3.1.5 and began to get some syntax errors.

For example, when I use properties `user` and `group` inside the `service`, I get an error.

Example:
```ruby
systemd_service 'testing' do
  unit_description 'testing'
  unit_after %w( syslog.target network.target )

  install do
    wanted_by 'multi-user.target'
  end

  service do
    type 'simple'
    user 'hugo.cisneiros'
    group 'hugo.cisneiros'
    exec_start '/bin/echo testing'
  end
end
```

Error:

```
    systemd_unit[testing] (/var/cache/chef/cookbooks/systemd/libraries/resource_factory.rb line 59) had an error: NoMethodError: undefined method `[]' for nil:NilClass
```

When I use the properties outside the `service` property, it works:

```
service_user 'hugo.cisneiros'
service_group 'hugo.cisneiros'
```

Should the `user` and `group` work inside the property?

Also, I had to change every resource that has `description` (used to work on cookbook version 2.0.0) to `unit_description`. Maybe it should work like `after` that works as `after` and `unit_after` too?

Thanks!

**Comment by nathwill** [comment]
yeah, the mapping from #user to #service_user inside the service block relies on the [method_missing functionality](https://github.com/nathwill/chef-systemd/blob/master/libraries/mixin.rb#L32-L38). so, unfortunately, properties that exist on core chef resources or the systemd_unit resource don't trip the method_missing redirect of the user property call, necessitating the use of the full service_user property.

i'm not thrilled about it, but haven't come up with a great solution yet either...

thankfully, the number of property names that overlap with parent-class properties is very small... unfortunately, they're also heavily used (e.g. user/group) 😭, but ce la viv.

**Comment by nathwill** [comment]
as for description, that would need to go inside a unit block (like the service block) or be called as "unit_description" like you noted. 

the reason for the change in v3+ is that some unit properties are duplicated within different sub-sections of the same unit type (particularly in the networking related unit types), so the only proper way to handle it is to require sub-section specification in either the method name or a surrounding block.

**Comment by nathwill** [comment]
so i did some looking around and talked with the inestimable Noah K, and he gave me some pointers on how to fix this. i'm not sure when exactly i'll have the time to sit down and rework this part of the resource, but for now i'll flag this as a bug and try to prioritize some time to fix this asap.

**Comment by nathwill** [comment]
@hugo-cisneiros-movile so i just pushed a solution for this in 3.2.0, do you want to give it a try?
